### ISSUE TITLE
Missing django.contrib.auth.mixins

### ISSUE THREAD

**Issue by nim65s** [refreshoxford/django-cbv-inspector#103]
Hi,

Django 1.9 defines `AccessMixin`, `LoginRequiredMixin`, `PermissionRequiredMixin`, and `UserPassesTestMixin`, and it lacks some docs… Could we have it on ccbv.co.uk ? :D

**Comment by exonian** [comment]
Hi

Great spot: those would be great to have on the site.

This seems to be very closely related to #89 (which has a helpful reply from @meshy already). I'm not sure whether anyone did any work on resolving that, but presumably if someone wants to work on either of the tickets, the work to address one will basically all-but-resolve the other, too.

**Comment by ghickman** [comment]
These are now live, thanks to @exonian!
