### ISSUE TITLE
Update Various Sections of Project

### ISSUE THREAD

**Issue by ghickman** [refreshoxford/django-cbv-inspector#107]
Having tried to deploy @exonian's changes from #105 & #106 it looks like the project could do with some house keeping. Unfortunately the staticfiles configuration doesn't work in production (the deploy actually fails which is useful!) due to a dep that disappeared from Django in 1.7. Let's take the opportunity to upgrade all the way to 1.9 while we're at it too.

* [x] Upgrade Django to 1.9
* [x] Remove s3 config
* [x] Switch all static files config to [whitenoise](https://pypi.python.org/pypi/whitenoise/3.0)
* [x] Rearrange the settings file so it looks like a 1.9 template project, removing all the unnecessary settings.
* [x] Switch to django cache url
* [x] Flip installed apps around so it third party projects the cbv app override the django apps
* [x] Use pip-tools for requirements (document how to pip compile)
* [x] Remove old deps (south, django-storages, etc)
* [x] Remove `patterns` in URLs
* [x] Remove admin auto discovery
* [x] Modernise wsgi.py, manage.py
* [x] Update Procfile to use gunicorn directly
* [x] Pin python runtime for Heroku
* [x] Move to Opbeat

**Comment by meshy** [comment]
Sounds great! Only thing: it might be a better idea to stick with the LTS version of django.

**Comment by ghickman** [comment]
@meshy – what's your reasoning for sticking with LTS releases?

**Comment by exonian** [comment]
Ach sorry about that. Do we want to roll it back to 1.5 and get the changes deployed or do we think we'll get this upgrade out the door pretty quickly?

**Comment by meshy** [comment]
@ghickman We created the site on `1.3` and stopped updating it when we got to `1.5`. LTS means we get to wait for longer before we need to update again.

**Comment by ghickman** [comment]
@exonian – not really your fault! The static stuff is pretty legacy now and the production stuff appears to be hidden when running in dev. I'm hoping to get these updates done pretty soon.

@meshy – Given the new release schedule we'll still be updating from LTS to LTS quicker than we updated from 1.3 to 1.5 ;) I'm a fan of small regular updates rather than large updates infrequently.

**Comment by meshy** [comment]
@ghickman well volunteered! :trollface:

**Comment by ghickman** [comment]
Started work in `house-keeping`.
