### ISSUE TITLE
Does this suppose to be a generic tool for other django projects?

### ISSUE THREAD

**Issue by iamsk** [refreshoxford/django-cbv-inspector#113]
I see `https://github.com/vintasoftware/cdrf.co` is heavily based on this, but changed a lot, is there a easy way to do this?

**Comment by ghickman** [comment]
@iamsk – The current version is heavily tied to `django.views.generic` and related mixins (they're defined in settings).  I've been working on a static generation tool that's a lot less tied to that particular section.  You can see the work on the `static-pages-requiem` if you're interested, however it's not complete yet.

**Comment by iamsk** [comment]
@ghickman Thanks for your reply, I will read the code.
