### ISSUE TITLE
Use a canonical tag to make 1.11 the default search value.

### ISSUE THREAD

**Issue by YPCrumble** [refreshoxford/django-cbv-inspector#124]
Thanks for creating this library! I use it almost every week. I have a small suggestion regarding user experience coming from Google. 

Currently when I search "CreateView" I get versions 1.4 and 1.5 of CCBV: https://cl.ly/3b3Y1g2Z3j3Z

Django solves this by using a canonical tag on versions prior to 1.11 that point to 1.11. For instance here on https://docs.djangoproject.com/en/1.10/topics/class-based-views/generic-editing/

https://cl.ly/38032E322D2e

`<link rel="canonical" href="https://docs.djangoproject.com/en/1.11/topics/class-based-views/generic-editing/">`

I think CCBV should do the same - it would avoid any possible duplicate content penalty for pages that are mostly the same, and be helpful to the user since every time I visit the site from Google I have to change the default from an old version.

Happy to make a PR if that's helpful!

**Comment by exonian** [comment]
Superb suggestion! Thanks @YPCrumble 

Yes, a PR would be very much appreciated! If you run into any issues, let us know and someone will try to help, but if you can carry this forward that'd be brilliant.
