### ISSUE TITLE
https://www.ccbv.co.uk is down

### ISSUE THREAD

**Issue by polarise** [refreshoxford/django-cbv-inspector#129]
Hi,

Could someone please check out why the webpage for CCBV is down? 

"You only miss the water when the well runs dry"

Paul

**Comment by meshy** [comment]
Hi there. Sorry for the inconvenience -- CCBV is running on the free tier of Heroku, and has overrun its dyno-budget for this month. We're looking into short-term and long-term fixes for this. Please bear with us. At the worst, it should be back up on new year's day, when the quota is reset.
