### ISSUE TITLE
Latest Django Version: 3.1

### ISSUE THREAD

**Issue by raratiru** [refreshoxford/django-cbv-inspector#145]
The latest Django version is not included in the [Classy Class-Based Views](https://ccbv.co.uk/) web site.

**Comment by meshy** [comment]
Thanks for the report @raratiru -- you're right, I've not been able to get around to updating the site recently. I hope to get on this soon, assuming one of the other maintainers doesn't jump in there first.

Apologies for the delay.

**Comment by raratiru** [comment]
OK, thank you!

**Comment by meshy** [comment]
Done! New docs for Django 3.1 have been built, and are live. Thanks again for the bump!
