### ISSUE TITLE
I sure would appreciate a dark theme

### ISSUE THREAD

**Issue by Asday** [refreshoxford/django-cbv-inspector#146]
Black on white makes sense for paper because it's cheaper ink-wise, and the light source is somewhere else, so the white is nicely diffuse.

Computer screens are (mostly) lightbulbs, not paper.  When I'm looking at one, a great deal of light is directed straight into my eyeballs.  This is not comfortable for extended periods of time.

Here are how some tools I use during my day look:

* docker docs

![image](https://user-images.githubusercontent.com/340276/109327608-6c064880-7850-11eb-978d-638031b7fb58.png)

* my text editor

![image](https://user-images.githubusercontent.com/340276/109327816-a7087c00-7850-11eb-9228-36b255486bf4.png)

* gitlab

![image](https://user-images.githubusercontent.com/340276/109327964-d0290c80-7850-11eb-8a7c-6072d77f281c.png)

* github

![image](https://user-images.githubusercontent.com/340276/109328003-db7c3800-7850-11eb-88e0-a4f0f3555d85.png)

* CCBV

![image](https://user-images.githubusercontent.com/340276/109328096-f8b10680-7850-11eb-82fb-fd9d4fc26ae0.png)

**Comment by meshy** [comment]
Hi @Asday, thanks for the suggestion, though I don't want to alter the theme of this website, I'm afraid.

I suggest you install a plugin for your browser to alter the themes of websites you access -- that way individual websites don't need to change to suit your preferences.

For example, I occasionally use [Dark Reader](https://addons.mozilla.org/en-US/firefox/addon/darkreader/) for Firefox. I expect there are alternatives for the other major browsers, if you use them instead.
