### ISSUE TITLE
Permalinks to methods

### ISSUE THREAD

**Issue by jturnbull** [refreshoxford/django-cbv-inspector#37]
http://ccbv.co.uk/projects/Django/1.4/django.views.generic.edit/FormView/#dispatch

Should open up the dispatch method so I can send it to someone.

As per Django, it would also be nice if a clickable ¶ appeared so we could easily get the permalink.

_even better_, I'd link to link direct to lines of the code within the method (like on Github).

**Comment by mkoistinen** [comment]
Closed by #118
