### ISSUE TITLE
Ficstures docstrings in classes with month in names shows incorectly years

### ISSUE THREAD

**Issue by sztosz** [refreshoxford/django-cbv-inspector#87]
https://github.com/refreshoxford/django-cbv-inspector/blob/master/cbv/fixtures/1.6.json

Line 404 is: "docstring": "List of objects published in a given year.", 
Line 404 should be "docstring": "List of objects published in a given month.", 

Line 533 is: "docstring": "List of objects published in a given year.", 
Line 533 should be "docstring": "List of objects published in a given month.",

**Comment by ghickman** [comment]
All fixtures got updated recently in #106 so I'm assuming this is fixed.

Please feel free to reopen this if there are any inconsistencies with core.
