### ISSUE TITLE
Add inspection for WizardView

### ISSUE THREAD

**Issue by ralphje** [refreshoxford/django-cbv-inspector#89]
While developing a wizard I noticed that the `django.contrib.formtools.wizard.views.WizardView` and subclasses are not present on ccbv.co.uk. Perhaps these should be added?

**Comment by exonian** [comment]
`formtools` is no longer at `django.contrib.formtools` and is now a third-party package. So it's no longer just a case of adding the ability to import from multiple places within Django (although we should totally do that: I might have a bash this holiday), it'd be an extension into inspecting views from third party packages. Which might well be worth doing, but it's now a much bigger chunk of work I think.

**Comment by ghickman** [comment]
Thanks to @exonian these are now available on the appropriate Django versions!
